version: '3'

services:
  node-installer:
    build:
      context: ./.docker
      dockerfile: Dockerfile.node-installer
    volumes:
      - ./node_modules:/node_modules
      - ./my-medusa-store:/my-medusa-store
      - ./my-medusa-storefront:/my-medusa-storefront
      - ./medusa-admin:/medusa-admin

  medusa-admin:
    container_name: medusa-admin
    build:
      context: ./medusa-admin
      dockerfile: Dockerfile.dev
    ports:
      - "7000:7000"
    volumes:
      - ./node_modules:/app/node_modules
      - ./medusa-admin:/app/medusa-admin
    depends_on:
      node-installer:
        condition: service_completed_successfully
    networks:
      - medusa

  server:
    container_name: server
    build:
      context: ./my-medusa-store
      dockerfile: Dockerfile.dev
    ports:
      - "9000:9000"
    volumes:
      - ./node_modules:/app/node_modules
      - ./my-medusa-store:/app/my-medusa-store
    depends_on:
      node-installer:
        condition: service_completed_successfully
      postgres:
        condition: service_started
    networks:
      - medusa

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: development
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PORT: 5432
    ports:
      - 5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
    networks:
      - medusa

  redis:
    image: redis
    expose:
      - 6379

#volumes:

networks:
  medusa:
