FROM node:14-alpine as development

WORKDIR /app/my-medusa-store

EXPOSE 9000

RUN apk add --no-cache bash
# auto install dependencies within volume and run
CMD ["/bin/bash", "-c", "([[ -d ./node_modules/.bin ]] || yarn; yarn run start)"]
