FROM node:14-alpine as development

WORKDIR /app/medusa-admin

EXPOSE 7000

RUN apk add --no-cache bash
# auto install dependencies within volume and run
CMD ["/bin/bash", "-c", "([[ -d ./node_modules/.bin ]] || yarn; yarn rebuild --verbose sharp; yarn run start)"]
